---

# Setup Oracle Linux Server

- hosts: localhost
  gather_facts: true
  become: true
  become_method: sudo

  roles:
  - { role: setup_linux, tags: [ 'setup', 'linux'] }
  - { role: setup_ansible, tags: [ 'setup', 'ansible'] }
  - { role: setup_oracle, tags: [ 'setup', 'oracle'] }

- hosts: localhost
  gather_facts: true
  become: true
  become_user: oracle

  roles:
  - { role: setup_oraUser, tags: [ 'setup', 'oracle'] }

